### ISSUE TITLE
add photos along a trip route

### ISSUE THREAD

**Issue by ryanbranciforte** [trailheadlabs/carlessca#10]
We need to be able to place and display the photos along a route. Ideally OS would allow the user to do that manually and via gps. I'll add a separate ticket in carless, but will apply to OS as well.

similar to how strava does it seems to be pretty standard. 

![screen shot 2015-12-19 at 1 06 06 am](https://cloud.githubusercontent.com/assets/2602563/11912332/cac833e2-a5ec-11e5-8b4b-b8dd63932f8b.png)

**Comment by jmoe** [comment]
this is done, I followed the same design as for the other features in the map. clicking on a photo marker will make that photo appear in the carousel.
