### ISSUE TITLE
Additional Info Expand/Collapse

### ISSUE THREAD

**Issue by jmoe** [trailheadlabs/carlessca#11]
This section should start out collapsed? Should expand when container is clicked.

**Comment by ryanbranciforte** [comment]
Yeah, let's test out with section collapses as the default. There is a "+" button that when clicked expands the section, but could expand if user clicks anywhere in the container if we want to try that.

**Comment by jmoe** [comment]
That is implemented.

**Comment by ryanbranciforte** [comment]
looking great! 

one issues is that i can't seem to unexpand the trip once it has been expanded.

**Comment by jmoe** [comment]
yeah, I think the idea is that it you would just choose a different trip

**Comment by jmoe** [comment]
Also, I think what you are describing is unrelated to the Additional Info section. So if something needs to be done relating to trips file another issue.

**Comment by ryanbranciforte** [comment]
will do
