### ISSUE TITLE
start > destination options

### ISSUE THREAD

**Issue by ryanbranciforte** [trailheadlabs/carlessca#13]
these are the options:

South Lake Tahoe
1. sacramento > south lake tahoe
2. sf > south lake tahoe

Yosemite
3. central valley > yosemite
4. sf > yosemite

there is not a sacto to yosemite or a central valley to south lake tahoe option

**Comment by jmoe** [comment]
cool, made that update. what should the default from locations be?

**Comment by ryanbranciforte** [comment]
there should not be a sacto to yosemite option

http://carless.transitandtrails.org/to/yosemite/from/sacramento

i notice the central valley in the dropdown, but it turns into sacto when selected

defaults should be:
sacramento to south lake tahoe
central valley to yosemite

**Comment by jmoe** [comment]
Pushed a fix for that.

**Comment by ryanbranciforte** [comment]
still seeing 
http://carless.transitandtrails.org/to/south_lake_tahoe/from/central_valley
http://carless.transitandtrails.org/to/yosemite/from/sacramento

might add those in the future, but they shouldn't be options right now

make sense?

**Comment by jmoe** [comment]
Not sure I what you mean by "still seeing" those links. Where are you seeing them? The page is dynamic.

**Comment by jmoe** [comment]
OK, I _think_ this is resolved. but please check again.

**Comment by ryanbranciforte** [comment]
Looking good. 

A few changes:
1. when a user clicks on south lake tahoe on the home page, can we have the landing page be: http://carless.transitandtrails.org/to/south_lake_tahoe/from/sacramento
2. when a user clicks on yosemite on the home page, can we have the landing page be: 
   http://carless.transitandtrails.org/to/yosemite/from/central_valley
3. Can we change San Francisco -> San Francisco Bay Area

**Comment by ryanbranciforte** [comment]
can we have the default starting point for yosemite be merced and for tahoe be sacto? both are set to sf as the default starting point.
