### ISSUE TITLE
Destination Summary Photos and Text

### ISSUE THREAD

**Issue by jmoe** [trailheadlabs/carlessca#15]
Need to choose a square summary photo and some text for the destination summary section on the destination pages.

**Comment by jmoe** [comment]
![screenshot 2015-12-22 08 13 41](https://cloud.githubusercontent.com/assets/74224/11959774/15107fe2-a884-11e5-82f4-83fc5da08851.png)

**Comment by ryanbranciforte** [comment]
Draft copy in this google doc:

https://docs.google.com/document/d/1XHzdttGlmlPIh9DLc1u7gS57kCfJDkFJEwkZB20-kIo/edit

**Comment by jmoe** [comment]
I have updated the summary text and chose some photos.

**Comment by ryanbranciforte** [comment]
looking good.
