### ISSUE TITLE
Additional Info Copy

### ISSUE THREAD

**Issue by jmoe** [trailheadlabs/carlessca#17]
I need the additional info copy for the various from/to combinations.

**Comment by jmoe** [comment]
https://docs.google.com/document/d/1XHzdttGlmlPIh9DLc1u7gS57kCfJDkFJEwkZB20-kIo/edit?ts=5682ac67

**Comment by jmoe** [comment]
I have plugged in a lot of this. Going to open new issues for individual items left to do.

**Comment by ryanbranciforte** [comment]
sounds good.
