### ISSUE TITLE
Load Trips from OuterSpatial

### ISSUE THREAD

**Issue by jmoe** [trailheadlabs/carlessca#18]
The destination trips should load from OuterSpatial

**Comment by jmoe** [comment]
http://www.outerspatial.com/trips/1250/embed

**Comment by ryanbranciforte** [comment]
I started a google spreadsheet and will put trips in here moving forward. 
just cleaned this one up. http://www.outerspatial.com/trips/1252 

https://docs.google.com/a/trailheadlabs.com/spreadsheets/d/1SOSyCfo21Cjt8Adj4owQ-wm7farDAs5HqVl__L7qR8E/edit?usp=sharing

**Comment by jmoe** [comment]
I have create a CarLess application in OS and a CarLess organization. 

http://www.outerspatial.com/applications/16

http://www.outerspatial.com/organizations/carless-california

So, trips can be added to the website by making the organization a partner on a trip.

The region for the trip can be specified in an Application Property called 'properties' that looks like:

{
  "region":"south_lake_tahoe",
  "activity":"Hike",
  "elevation":"1020ft",
  "season":"Spring/Summer"
}

yosemite can also be specified for region.

This way we can add new trips to the site without a new deployment of code.

The trip details are reading from the OS API so when a change is made in OS it will be reflected on the CarLess site. The values are cached for 60 seconds, so there could be up to a second delay between updating on OS and appear on the site.
