### ISSUE TITLE
Extra Map Overlays

### ISSUE THREAD

**Issue by jmoe** [trailheadlabs/carlessca#19]
Need to load the extra overlays from CartoDB and MapBox

**Comment by ryanbranciforte** [comment]
i got yosemite lodging and south lake tahoe lodging datasets into cartodb. they are tagged as 'carless'. let me know if you have any issues finding them.

still working on food, water & bathrooms, and one i'm planning to add - gear rentals

**Comment by ryanbranciforte** [comment]
btw, i think we can have lodging include camping since all of the non-campground options we are suggesting in tahoe also have tent sites/camping options.

**Comment by ryanbranciforte** [comment]
just got in yosemite food/dining options in cartodb
next up tahoe dining options.

**Comment by jmoe** [comment]
i'm going to separate out the rest of the layers into their own issues. food, lodging and campging are working for yosemite.

**Comment by ryanbranciforte** [comment]
i noticed that camping in yosemite is not clickable. you can click on lodging and get info box, but not camping.
