### ISSUE TITLE
Banner photo

### ISSUE THREAD

**Issue by jmoe** [trailheadlabs/carlessca#2]
What photo are we going to use for the banner?

**Comment by ryanbranciforte** [comment]
on the home page?

we'll have to go through the photos and choose one. feel free to pick one. i'll reach out to lech and see if he has a preference. 

Yosemite photos - https://www.dropbox.com/sh/l81rfug9jc1k96q/AABuJ2VMc0j71LHUlWYds8Lla?dl=0
Tahoe photos - https://www.dropbox.com/sh/cpvkycksgedu4zm/AABp8woxwqB9HTLqWFhs2cWYa?dl=0

Let me know if you want me to invite you to the dropbox folders so you can have the photos locally.

**Comment by jmoe** [comment]
The one up there now is royalty free, from unsplash. Will defer to you on which other one to use.

**Comment by ryanbranciforte** [comment]
Cool.

**Comment by jmoe** [comment]
Let's close this and if you decide on a different one just create a new issue to replace it.
