### ISSUE TITLE
photo attribution

### ISSUE THREAD

**Issue by ryanbranciforte** [trailheadlabs/carlessca#23]
we need to add photo credits. 

i like out they do this on site jeff designed:

http://www.conservationalliance.com/success-stories/

![screen shot 2016-01-11 at 3 03 16 pm](https://cloud.githubusercontent.com/assets/2602563/12249470/d0db9cde-b874-11e5-8626-4444e6ade0dc.png)

click on the camera and the credits appear.

most of the photos will be from lechphoto, but we'll probably have some from other sources as well.

**Comment by ryanbranciforte** [comment]
lmk where to add photo attribution. lech is the photographer for most of the photos in there, but will also be getting some from 500px and maybe other places.

**Comment by jmoe** [comment]
photo attribution can be added to photos from the manage images section of outerspatial and they will show up on the images
