### ISSUE TITLE
transit layer

### ISSUE THREAD

**Issue by jmoe** [trailheadlabs/carlessca#24]
the transit custom layer needs to be done.
i need to update the transit stop database with the latest data.
then I need to cut that down to just the relevant agencies. 
ryan, did you send me the list of agencies somewhere? or can you just post it here. thanks.

**Comment by ryanbranciforte** [comment]
here is a google doc with transit agencies for the two corridors:

https://docs.google.com/spreadsheets/d/1lluTXpdZ1xBtc6M1hkxl4hRCy3-nw1NlV52s6pXEkP0/edit#gid=46723186

emerald bay shuttle is important for tahoe. the stops show up in OS now, so they must be in gtfs somewhere.

**Comment by jmoe** [comment]
I imported the lastest CA transit stops from GTFS data exchange and put those into CartoDB

**Comment by ryanbranciforte** [comment]
just an FYI, i went in and made some changes to the ca transit data in carto. all of the yose valley shuttle stops were empty so I added the bus name and link to agency site. for tahoe, there were many agencies serving the same stop and no info on the emerald bay shuttle so i added info on the shuttle for its stops.

**Comment by jmoe** [comment]
cool, yeah, I noticed the blanks, those all were just coming over from GTFS, so I guess those are low quality feeds. that layer is not auto-updated or anything, so it's OK to make changes.
