### ISSUE TITLE
Text descriptions for trips

### ISSUE THREAD

**Issue by jmoe** [trailheadlabs/carlessca#27]
Need to update the text descriptions for trips in outerspatial and use those

**Comment by jmoe** [comment]
@ryanbranciforte can you verify that the trips in OuterSpatial have good text descriptions?

**Comment by ryanbranciforte** [comment]
yes, they all have copy now. is it ok to change the copy in the future? i might update some of them over time. 

should we stick to a general length? right now some are short and some are long.

which description field are you pulling from? 

is it possible to have links in the descriptions? that would be good as a lot of the descriptions have links.
