### ISSUE TITLE
Tahoe cost section

### ISSUE THREAD

**Issue by jmoe** [trailheadlabs/carlessca#29]
This section needs to be reworked based on the design, the content in the doc does not really fit the design

**Comment by ryanbranciforte** [comment]
Need to update the cost section for Tahoe, we have the yosemite cost stuff in there now. 

http://carless.transitandtrails.org/to/south_lake_tahoe/from/sacramento

this copy is in the google doc

https://docs.google.com/document/d/1XHzdttGlmlPIh9DLc1u7gS57kCfJDkFJEwkZB20-kIo/edit

but i've pasted below here as well

This is for starting from Sacramento:

Cost (from Sacramento)
Sacramento to South Lake Tahoe on Amtrak Thruway Bus  -> $68 round trip, $34 one-way 
Child (12 & under) = $34 round trip, $17 one-way
Senior (62+) = $57.80 round trip, $28.90 one-way
*Amtrak frequently offers deals and has numerous discounts for students, military, etc. See more info here (http://yarts.com/tickets-and-fares/).

**Comment by ryanbranciforte** [comment]
and for starting from SF:

Cost (from San Francisco Bay Area)
Richmond to South Lake Tahoe on Amtrak Thruway Bus  -> $102 round trip, $51 one-way 
Child (2-12) = $51 round trip, $25.50 one-way
Senior (62+) = $88 round trip, $44 one-way
*Amtrak frequently offers deals and has numerous discounts for students, military, etc. See more info here (http://yarts.com/tickets-and-fares/).
