### ISSUE TITLE
Yosemite cost section

### ISSUE THREAD

**Issue by jmoe** [trailheadlabs/carlessca#30]

**Comment by ryanbranciforte** [comment]
http://carless.transitandtrails.org/to/yosemite/from/san_francisco

For the SF to Yosemite 'additional info' section we have the cost from Richmond to Merced, but we need to add the cost of Merced to Yosemite, which is just the same copy from the sacramento to SF page. 

So, add this:
![screen shot 2016-03-02 at 2 38 38 pm](https://cloud.githubusercontent.com/assets/2602563/13478184/b688ce50-e084-11e5-9e46-15681de691ae.png)

Below what is already there. 

Oh, and add (Merced to Yosemite on YARTS) in parenthesis next to Adult. 

Make sense?
