### ISSUE TITLE
can we have links in the 'additional info' section?

### ISSUE THREAD

**Issue by ryanbranciforte** [trailheadlabs/carlessca#36]
![screen shot 2016-02-29 at 4 34 47 pm](https://cloud.githubusercontent.com/assets/2602563/13413822/62c5e84e-df02-11e5-8c29-b5307298a15a.png)

i have links in the copy, those would be very useful for users. if we can, have them open in a new page.

**Comment by jmoe** [comment]
We can, but they are very cumbersome to pull out of Google docs, requires lots of clicks. So, if there are lots it will take a while.

**Comment by ryanbranciforte** [comment]
lmk if there is a format that would be easier. i could put the full urls somewhere if helpful, just let me know

**Comment by ryanbranciforte** [comment]
i put the links in the google doc next to the work they are supposed to link from and highlighted in red so they were easier to pick out.
