### ISSUE TITLE
how are we handling elevation?

### ISSUE THREAD

**Issue by ryanbranciforte** [trailheadlabs/carlessca#37]
i am putting elevation info in this doc for now? let me know if i should put it somewhere else. i still need to track down for a few of the trips, doing that soon. 

https://docs.google.com/document/d/1ietw6I4PJFUINtkTC2CLTOvHAp1fam1lb7HRq8c_Nb0/edit

**Comment by jmoe** [comment]
Elevation comes from an application property called 'elevation' so please put those values there.

**Comment by ryanbranciforte** [comment]
got it

**Comment by ryanbranciforte** [comment]
i've added elevation for all the trips
