### ISSUE TITLE
can't add attribution to photos

### ISSUE THREAD

**Issue by ryanbranciforte** [trailheadlabs/carlessca#38]
i tried to add Lech's name to the attribution text for a few photos and it sends me to error page

http://www.outerspatial.com/images/3137

![screen shot 2016-02-29 at 8 42 45 pm](https://cloud.githubusercontent.com/assets/2602563/13417962/6c324404-df25-11e5-976b-036bff505922.png)

**Comment by ryanbranciforte** [comment]
fyi, it seems to work fine if you add attribution text and location, but gives the error page when you add just the attribution text

**Comment by jmoe** [comment]
Pushed a fix.

**Comment by ryanbranciforte** [comment]
working now!
