### ISSUE TITLE
we need photo attribution on the home page and destination pages in carless

### ISSUE THREAD

**Issue by ryanbranciforte** [trailheadlabs/carlessca#39]
http://carless.transitandtrails.org/ btw, where is that home page photo from? do we have permission to use it?

http://carless.transitandtrails.org/to/south_lake_tahoe

http://carless.transitandtrails.org/to/yosemite

we have implemented photo attribution on the napaoutdoors site, works well. i'm sure riley could get you the code he used to implement if helpful. lmk if you want an intro email. 

![screen shot 2016-02-29 at 8 50 41 pm](https://cloud.githubusercontent.com/assets/2602563/13418027/1e04619e-df26-11e5-8d32-a71b67c368fe.png)

**Comment by jmoe** [comment]
The photo on the homepage is from Unsplash, royalty free images. 

https://unsplash.com/license

If we try to cram the attribution at the bottom of the images on the destination pages it's going to crowd the menus. I suggest we drop something in the upper right hand corner.

**Comment by ryanbranciforte** [comment]
sounds good. upper right may get in way of the social media icons, but your call.

**Comment by jmoe** [comment]
sorry, meant upper right

**Comment by jmoe** [comment]
upper left!

**Comment by jmoe** [comment]
Pushed

**Comment by ryanbranciforte** [comment]
cool
