### ISSUE TITLE
Social media links

### ISSUE THREAD

**Issue by jmoe** [trailheadlabs/carlessca#4]
There are a bunch of social media links in the designed navigation, where do these go? Need URLs.

**Comment by ryanbranciforte** [comment]
I'll check with carless team, but I don't think they have a social media presence for carless so I think we could have them go to T&T or THL's social media.

**Comment by jmoe** [comment]
OK, let me know once you have decided.

**Comment by jmoe** [comment]
Right now they are linking to Trailhead Labs stuff.

**Comment by jmoe** [comment]
Will close this and if we need to change them just open an issue for it.

**Comment by ryanbranciforte** [comment]
Sounds good.
