### ISSUE TITLE
'hike' broken up into two lines

### ISSUE THREAD

**Issue by ryanbranciforte** [trailheadlabs/carlessca#43]
i checked the description in OS and there is no space

![screen shot 2016-02-29 at 9 50 27 pm](https://cloud.githubusercontent.com/assets/2602563/13418900/87593086-df2e-11e5-91c3-6eaddb4da510.png)

**Comment by jmoe** [comment]
Pushed a fix.

**Comment by ryanbranciforte** [comment]
thnks
