### ISSUE TITLE
formatting issue with baview campground

### ISSUE THREAD

**Issue by ryanbranciforte** [trailheadlabs/carlessca#47]
![screen shot 2016-03-01 at 5 11 29 pm](https://cloud.githubusercontent.com/assets/2602563/13447479/b233076c-dfd0-11e5-9600-c71f05623dbb.png)

Bayview should be highlighted like the other campgrounds.

**Comment by jmoe** [comment]
Not sure I understand. What trip is this?

**Comment by jmoe** [comment]
I'm also not sure what you mean by "highlighted", please clarify.

**Comment by ryanbranciforte** [comment]
sorry, this is from the 'additional info' section of lake tahoe

http://carless.transitandtrails.org/to/south_lake_tahoe

bayview campground should look like 'meeks bay' and the other lodging opportunities

![screen shot 2016-03-01 at 10 59 57 pm](https://cloud.githubusercontent.com/assets/2602563/13452955/7d344842-e001-11e5-97f5-1bb952d896f5.png)
