### ISSUE TITLE
photo attribution not showing up

### ISSUE THREAD

**Issue by ryanbranciforte** [trailheadlabs/carlessca#49]
i added lech as photographer, but he's not showing up in the images:

![screen shot 2016-03-01 at 5 34 44 pm](https://cloud.githubusercontent.com/assets/2602563/13447922/f275e51c-dfd3-11e5-874e-1b17dac4364d.png)

this is the historic tahoe by bike trip, but happening with others as well

**Comment by ryanbranciforte** [comment]
it seems the issue is when i edit the image and add the attribution. it is not saving. i've done like 50 of these before i realized it was not saving b/c it gives the confirmation at the top. ugh!

![screen shot 2016-03-01 at 5 42 04 pm](https://cloud.githubusercontent.com/assets/2602563/13448069/f690f8de-dfd4-11e5-8c1f-f40bf99f6b57.png)

![screen shot 2016-03-01 at 5 42 15 pm](https://cloud.githubusercontent.com/assets/2602563/13448073/fc515afc-dfd4-11e5-9e00-3714f2421c86.png)

**Comment by jmoe** [comment]
I need some URLs, always.

**Comment by jmoe** [comment]
I see what happened. This broken when I added the 500px attribution support.

**Comment by jmoe** [comment]
Fixed now.

**Comment by ryanbranciforte** [comment]
working now
