### ISSUE TITLE
how do you know which ones are under which license?

### ISSUE THREAD

**Issue by ryanbranciforte** [trailheadlabs/carlessca#50]
or is it only searching creative commons photos?

![screen shot 2016-03-01 at 5 44 59 pm](https://cloud.githubusercontent.com/assets/2602563/13448134/5ec06d72-dfd5-11e5-864f-62bc585c2084.png)

**Comment by jmoe** [comment]
It's showing them all, because I thought you were going to take the strategy of contacting the photographers. How would you like this to work now?

**Comment by ryanbranciforte** [comment]
for 500px, it would be useful to be able to filter by license via the dropdown. that way if there happens to be a nice enough photo that is creative commons, i can pull it in. we can hold off for now on flickr and instagram, but soon we can do something similar for those once we figure out the license issue

also, would be useful to have the photo link to the 500px page so we could see the cost.

where do we find the user's contact info?

**Comment by jmoe** [comment]
I've added a license filter to the 500px finder. Use the value 4,5 to find CC photos (don't get your hopes up). Here are the valid license values:
ID  License Type
0   Standard 500px License
1   Creative Commons License Non Commercial Attribution
2   Creative Commons License Non Commercial No Derivatives
3   Creative Commons License Non Commercial Share Alike
4   Creative Commons License Attribution
5   Creative Commons License No Derivatives
6   Creative Commons License Share Alike

You can combine them with commas.

I've made the photographers name in the show image window a link to the photo page, where you can find pricing.
