### ISSUE TITLE
two trips missing from carless yosemite

### ISSUE THREAD

**Issue by ryanbranciforte** [trailheadlabs/carlessca#51]
http://www.outerspatial.com/trips/1246

http://www.outerspatial.com/trips/1319

**Comment by jmoe** [comment]
Those trips were not on the CarLess organization. So I added them.

**Comment by jmoe** [comment]
1319 also seems to be missing a starting trailhead, is that intentional? Seems odd.

**Comment by ryanbranciforte** [comment]
cool. fixed th start
