### ISSUE TITLE
photo attribution on destination pages in mobile formatting issue

### ISSUE THREAD

**Issue by ryanbranciforte** [trailheadlabs/carlessca#54]
![img_5183](https://cloud.githubusercontent.com/assets/2602563/13486132/1ef76daa-e0c3-11e5-8cfd-9e534474c9e2.PNG)
![img_5182](https://cloud.githubusercontent.com/assets/2602563/13486131/1ef58b7a-e0c3-11e5-8a12-fd9a09dafd07.PNG)

any thoughts on best way to fix this? 

can we have the attribution move to bottom center or upper right under the social media buttons or maybe just disappear when the site is viewed on mobile device?

**Comment by jmoe** [comment]
Just pushed out a fix to put this on the lower right, seems to work well.

**Comment by ryanbranciforte** [comment]
looks good!
