### ISSUE TITLE
Need all photo assets

### ISSUE THREAD

**Issue by jmoe** [trailheadlabs/carlessca#6]
Where are all of the photo assets for CarLess? 

Banner images for Yosemite and Tahoe

**Comment by ryanbranciforte** [comment]
Yosemite photos - https://www.dropbox.com/sh/l81rfug9jc1k96q/AABuJ2VMc0j71LHUlWYds8Lla?dl=0
Tahoe photos - https://www.dropbox.com/sh/cpvkycksgedu4zm/AABp8woxwqB9HTLqWFhs2cWYa?dl=0

Let me know if you want me to invite you to the dropbox folders so you can have the photos locally.

**Comment by jmoe** [comment]
Have all of these been associated with trips in outerspatial?

**Comment by ryanbranciforte** [comment]
No, I added photos to the bayview trail loop, that's it. I'll work on getting some more trips together this week.

**Comment by jmoe** [comment]
Are you still working on uploading all of the photos to the trips?

**Comment by ryanbranciforte** [comment]
Yes. Does every trip need a photo? or will the site work ok if a trip doesn't have photos?
