### ISSUE TITLE
change 'excursion' to 'excursions' in the Top Accessible section on the yosemite page.

### ISSUE THREAD

**Issue by ryanbranciforte** [trailheadlabs/carlessca#63]
http://carless.transitandtrails.org/to/yosemite/from/san_francisco
http://carless.transitandtrails.org/to/yosemite/from/central_valley

![screen shot 2016-03-21 at 11 10 47 am](https://cloud.githubusercontent.com/assets/2602563/13929181/18967fe0-ef56-11e5-80c1-bb3e4a007eac.png)

**Comment by jmoe** [comment]
Pushed a fix.

**Comment by ryanbranciforte** [comment]
looks good, thanks
