### ISSUE TITLE
Partner logos and links

### ISSUE THREAD

**Issue by jmoe** [trailheadlabs/carlessca#9]
Can you send me the logos and URLs for the partner section?

**Comment by ryanbranciforte** [comment]
i need to confirm that the agency's want their logos on the site. 

so these may change, but here they are:

Dropbox/THL/Customers/CarLess CA/partner_logos

usfs - http://www.fs.fed.us/
nps - http://www.nps.gov/index.htm
blm - http://www.blm.gov/wo/st/en.html
usfws - http://www.fws.gov/
sierra nevada geotourism - http://www.sierranevadageotourism.org/
california state university chico - http://www.csuchico.edu/
trailhead labs - i guess we should add, unless we have our logo/brand somewhere else

**Comment by jmoe** [comment]
I'll get these ready, put them up and them we can just take them down if we need to. Sound good?

**Comment by ryanbranciforte** [comment]
sounds good.

**Comment by jmoe** [comment]
I have pushed this.

**Comment by ryanbranciforte** [comment]
Looks good! 

One thing I noticed. My cursor turns to a zoom tool when I hover over and click the icons. Seems that should be the little hand.
